#!/usr/bin/env bash
# Regenerate the nginx auth/limit layer from customers.tsv.
#
# Why this exists: the endpoint previously had ONE shared key with no identity,
# no quota and no rate limit. That is unsafe to hand to real customers:
#   - a leak by any one of them compromises everybody, and rotating the key
#     breaks every client at once
#   - a single caller could (verified) fire 40 concurrent requests with zero
#     throttling, and hold a decode slot for hours with max_tokens=120000
#
# Per-customer keys give per-customer revocation, attribution in the access
# log, and per-customer concurrency + rate caps.
#
# Usage:  ./gen-keys.sh                 regenerate from customers.tsv
#         ./gen-keys.sh add <name>      mint a new customer key
#         ./gen-keys.sh revoke <name>   remove a customer
set -uo pipefail

TSV=/scratch/deploy/customers.tsv
UPSTREAM_KEY=$(cat /scratch/deploy/api-key.txt)
OUT=/etc/nginx/conf.d/00-k3-keys.conf

# Per-customer ceilings.
#
# These are sized for a KEY SHARED BY A WHOLE PORTAL, not one developer: many
# end users sit behind a single credential, so the cap has to bound a crowd
# rather than an individual. 200 concurrent against max-num-seqs 512 means one
# portal key can hold ~39% of the engine's sequence slots.
#
# The rate cap must scale with the connection cap or it becomes the real
# limit: at 10r/s a portal allowed 200 concurrent calls would still have been
# throttled after ten requests in a second. 100r/s matches what 200 in-flight
# requests can actually turn over (~3s each => ~67/s), and the burst absorbs
# the login-time stampede when many users reconnect at once.
#
# GLOBAL_CONN is raised to max-num-seqs so a 200-connection portal cannot
# starve the other keys: at the old 256 it would have owned 78% of the edge.
PER_CUST_CONN=200
PER_CUST_RATE=100r/s
PER_CUST_BURST=200
GLOBAL_CONN=512

[ -f "$TSV" ] || { umask 077; printf '# customer\tapi_key\n' > "$TSV"; }

case "${1:-gen}" in
  add)
    name="${2:?usage: gen-keys.sh add <name>}"
    grep -qP "^${name}\t" "$TSV" && { echo "customer '$name' already exists"; exit 1; }
    key="sk-k3-${name}-$(openssl rand -hex 20)"
    printf '%s\t%s\n' "$name" "$key" >> "$TSV"
    chmod 600 "$TSV"
    echo "added '$name'"
    echo "  key: $key"
    ;;
  revoke)
    name="${2:?usage: gen-keys.sh revoke <name>}"
    grep -qP "^${name}\t" "$TSV" || { echo "no such customer '$name'"; exit 1; }
    sed -i "/^${name}\t/d" "$TSV"
    echo "revoked '$name' - takes effect on reload below"
    ;;
esac

# ---- emit the nginx map + limit zones ----
# 0640: these hold every live key in cleartext. nginx reads them as root at
# load, so the worker user never needs them.
umask 077
{
  echo "# GENERATED by gen-keys.sh - do not edit by hand."
  echo "# Source of truth: $TSV"
  echo
  echo "# 'Bearer sk-k3-<name>-<40 hex>' exceeds the default 64-byte bucket."
  echo "map_hash_bucket_size 256;"
  echo
  echo "# Authorization header -> customer id. Empty means unauthenticated."
  echo 'map $http_authorization $k3_customer {'
  echo '    default "";'
  while IFS=$'\t' read -r name key; do
    case "$name" in ''|\#*) continue;; esac
    [ -n "${key:-}" ] || continue
    printf '    "Bearer %s" "%s";\n' "$key" "$name"
  done < "$TSV"
  echo '}'
  echo
  echo "# Per-customer concurrency and request-rate caps, keyed on identity so"
  echo "# one customer cannot starve the others."
  echo 'limit_conn_zone $k3_customer zone=k3_percust:10m;'
  echo "limit_req_zone \$k3_customer zone=k3_rps:10m rate=${PER_CUST_RATE};"
  echo 'limit_conn_zone $server_name zone=k3_global:1m;'
  echo
  echo "# Attribution: who called, how long it took, what came back."
  echo 'log_format k3usage '"'"'$time_iso8601 cust=$k3_customer status=$status '"'"''
  echo '                   '"'"'path=$request_uri req_ms=$request_time up_ms=$upstream_response_time '"'"''
  echo '                   '"'"'in=$request_length out=$body_bytes_sent ip=$remote_addr'"'"';'
} > "$OUT"
chmod 640 "$OUT"

cat > /etc/nginx/conf.d/k3-limits.inc <<EOF
    # Applied inside the /v1/ location of every server block.
    limit_conn k3_percust ${PER_CUST_CONN};
    limit_conn k3_global  ${GLOBAL_CONN};
    limit_req  zone=k3_rps burst=${PER_CUST_BURST} nodelay;
    limit_conn_status 429;
    limit_req_status  429;

    # Swap the customer's credential for the single upstream credential that
    # vLLM knows (VLLM_API_KEY in vllm-k3.env). Without this, a customer key
    # passes nginx and then vLLM returns its own 401 - which is exactly what
    # happened on first setup. Doing it here means adding or revoking a
    # customer never requires a vLLM restart.
    proxy_set_header Authorization "Bearer ${UPSTREAM_KEY}";
EOF
chmod 640 /etc/nginx/conf.d/k3-limits.inc

n=$(grep -cvE '^\s*(#|$)' "$TSV")
echo "generated $OUT with $n customer key(s)"

if nginx -t 2>&1 | tail -1 | grep -q successful; then
    systemctl reload nginx && echo "nginx reloaded - changes are live"
else
    echo "NGINX CONFIG INVALID - not reloading:"; nginx -t 2>&1 | tail -5; exit 1
fi
